# roles/mariadb/tasks/main.yml
---


- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: root-password.yml

- include_tasks: replication.yml
  when: mariadb_ha_enabled is defined and mariadb_ha_enabled

- include_tasks: databases.yml
  when: (mariadb_ha_enabled is not defined) or (mariadb_ha_enabled is defined and inventory_hostname == "{{ mariadb_servers | first }}")

- include_tasks: users.yml
  when: (mariadb_ha_enabled is not defined) or (mariadb_ha_enabled is defined and inventory_hostname == "{{ mariadb_servers | first }}")

